const SONGS = [
  {
    "rank": 1,
    "title": "Blinding Lights",
    "artist": "The Weeknd",
    "streams": 5.26,
    "genre": "Synth-Pop",
    "year": 2019,
    "energy": 0.8,
    "danceability": 0.51,
    "valence": 0.33,
    "bpm": 171.0
  },
  {
    "rank": 2,
    "title": "Shape of You",
    "artist": "Ed Sheeran",
    "streams": 4.9,
    "genre": "Pop/Dancehall",
    "year": 2017,
    "energy": 0.65,
    "danceability": 0.83,
    "valence": 0.93,
    "bpm": 96.0
  },
  {
    "rank": 3,
    "title": "Someone You Loved",
    "artist": "Lewis Capaldi",
    "streams": 4.05,
    "genre": "Pop",
    "year": 2018,
    "energy": 0.45,
    "danceability": 0.6,
    "valence": 0.42,
    "bpm": 77.0
  },
  {
    "rank": 4,
    "title": "Sunflower",
    "artist": "Post Malone & Swae Lee",
    "streams": 3.98,
    "genre": "Hip-Hop/Pop",
    "year": 2018,
    "energy": 0.49,
    "danceability": 0.76,
    "valence": 0.84,
    "bpm": 93.0
  },
  {
    "rank": 5,
    "title": "One Dance",
    "artist": "Drake",
    "streams": 3.92,
    "genre": "Afrobeats/Pop",
    "year": 2016,
    "energy": 0.62,
    "danceability": 0.79,
    "valence": 0.68,
    "bpm": 100.0
  },
  {
    "rank": 6,
    "title": "Stay",
    "artist": "The Kid LAROI & Justin Bieber",
    "streams": 3.87,
    "genre": "Pop",
    "year": 2021,
    "energy": 0.8,
    "danceability": 0.59,
    "valence": 0.6,
    "bpm": 170.0
  },
  {
    "rank": 7,
    "title": "Believer",
    "artist": "Imagine Dragons",
    "streams": 3.76,
    "genre": "Alt Rock",
    "year": 2017,
    "energy": 0.86,
    "danceability": 0.33,
    "valence": 0.45,
    "bpm": 125.0
  },
  {
    "rank": 8,
    "title": "Rockstar",
    "artist": "Post Malone ft. 21 Savage",
    "streams": 3.72,
    "genre": "Hip-Hop",
    "year": 2017,
    "energy": 0.52,
    "danceability": 0.55,
    "valence": 0.13,
    "bpm": 159.0
  },
  {
    "rank": 9,
    "title": "Dance Monkey",
    "artist": "Tones and I",
    "streams": 3.69,
    "genre": "Pop",
    "year": 2019,
    "energy": 0.63,
    "danceability": 0.83,
    "valence": 0.73,
    "bpm": 98.0
  },
  {
    "rank": 10,
    "title": "Happier",
    "artist": "Marshmello & Bastille",
    "streams": 3.65,
    "genre": "EDM/Pop",
    "year": 2018,
    "energy": 0.82,
    "danceability": 0.62,
    "valence": 0.96,
    "bpm": 100.0
  },
  {
    "rank": 11,
    "title": "Senorita",
    "artist": "Shawn Mendes & Camila Cabello",
    "streams": 3.62,
    "genre": "Latin Pop",
    "year": 2019,
    "energy": 0.74,
    "danceability": 0.75,
    "valence": 0.75,
    "bpm": 117.0
  },
  {
    "rank": 12,
    "title": "Watermelon Sugar",
    "artist": "Harry Styles",
    "streams": 3.58,
    "genre": "Indie Pop",
    "year": 2019,
    "energy": 0.82,
    "danceability": 0.55,
    "valence": 0.74,
    "bpm": 95.0
  },
  {
    "rank": 13,
    "title": "Perfect",
    "artist": "Ed Sheeran",
    "streams": 3.55,
    "genre": "Pop/Folk",
    "year": 2017,
    "energy": 0.43,
    "danceability": 0.66,
    "valence": 0.41,
    "bpm": 95.0
  },
  {
    "rank": 14,
    "title": "Levitating",
    "artist": "Dua Lipa",
    "streams": 3.52,
    "genre": "Nu-Disco",
    "year": 2020,
    "energy": 0.82,
    "danceability": 0.7,
    "valence": 0.91,
    "bpm": 103.0
  },
  {
    "rank": 15,
    "title": "Heat Waves",
    "artist": "Glass Animals",
    "streams": 3.4,
    "genre": "Indie Pop",
    "year": 2020,
    "energy": 0.54,
    "danceability": 0.51,
    "valence": 0.58,
    "bpm": 80.0
  },
  {
    "rank": 16,
    "title": "Bad Guy",
    "artist": "Billie Eilish",
    "streams": 3.37,
    "genre": "Electropop",
    "year": 2019,
    "energy": 0.43,
    "danceability": 0.7,
    "valence": 0.56,
    "bpm": 135.0
  },
  {
    "rank": 17,
    "title": "Drivers License",
    "artist": "Olivia Rodrigo",
    "streams": 3.34,
    "genre": "Pop",
    "year": 2021,
    "energy": 0.43,
    "danceability": 0.59,
    "valence": 0.13,
    "bpm": 73.0
  },
  {
    "rank": 18,
    "title": "Circles",
    "artist": "Post Malone",
    "streams": 3.31,
    "genre": "Pop Rap",
    "year": 2019,
    "energy": 0.55,
    "danceability": 0.69,
    "valence": 0.72,
    "bpm": 121.0
  },
  {
    "rank": 19,
    "title": "Memories",
    "artist": "Maroon 5",
    "streams": 3.28,
    "genre": "Pop",
    "year": 2019,
    "energy": 0.36,
    "danceability": 0.76,
    "valence": 0.7,
    "bpm": 91.0
  },
  {
    "rank": 20,
    "title": "Shallow",
    "artist": "Lady Gaga & Bradley Cooper",
    "streams": 3.25,
    "genre": "Pop/Country",
    "year": 2018,
    "energy": 0.55,
    "danceability": 0.59,
    "valence": 0.37,
    "bpm": 96.0
  },
  {
    "rank": 21,
    "title": "As It Was",
    "artist": "Harry Styles",
    "streams": 3.22,
    "genre": "Indie Pop",
    "year": 2022,
    "energy": 0.73,
    "danceability": 0.52,
    "valence": 0.36,
    "bpm": 174.0
  },
  {
    "rank": 22,
    "title": "Dynamite",
    "artist": "BTS",
    "streams": 3.19,
    "genre": "Pop/Funk",
    "year": 2020,
    "energy": 0.77,
    "danceability": 0.74,
    "valence": 0.74,
    "bpm": 114.0
  },
  {
    "rank": 23,
    "title": "Flowers",
    "artist": "Miley Cyrus",
    "streams": 3.16,
    "genre": "Pop",
    "year": 2023,
    "energy": 0.74,
    "danceability": 0.74,
    "valence": 0.88,
    "bpm": 118.0
  },
  {
    "rank": 24,
    "title": "Counting Stars",
    "artist": "OneRepublic",
    "streams": 3.14,
    "genre": "Pop Rock",
    "year": 2013,
    "energy": 0.8,
    "danceability": 0.62,
    "valence": 0.58,
    "bpm": 122.0
  },
  {
    "rank": 25,
    "title": "Lucid Dreams",
    "artist": "Juice WRLD",
    "streams": 3.11,
    "genre": "Emo Rap",
    "year": 2018,
    "energy": 0.49,
    "danceability": 0.51,
    "valence": 0.22,
    "bpm": 84.0
  },
  {
    "rank": 26,
    "title": "Closer",
    "artist": "The Chainsmokers ft. Halsey",
    "streams": 3.08,
    "genre": "EDM/Pop",
    "year": 2016,
    "energy": 0.65,
    "danceability": 0.74,
    "valence": 0.77,
    "bpm": 95.0
  },
  {
    "rank": 27,
    "title": "Calm Down",
    "artist": "Rema & Selena Gomez",
    "streams": 3.02,
    "genre": "Afrobeats/Pop",
    "year": 2022,
    "energy": 0.72,
    "danceability": 0.8,
    "valence": 0.78,
    "bpm": 106.0
  },
  {
    "rank": 28,
    "title": "Anti-Hero",
    "artist": "Taylor Swift",
    "streams": 2.99,
    "genre": "Indie Pop",
    "year": 2022,
    "energy": 0.58,
    "danceability": 0.64,
    "valence": 0.47,
    "bpm": 97.0
  },
  {
    "rank": 29,
    "title": "Save Your Tears",
    "artist": "The Weeknd",
    "streams": 2.88,
    "genre": "Synth-Pop",
    "year": 2020,
    "energy": 0.82,
    "danceability": 0.68,
    "valence": 0.78,
    "bpm": 118.0
  },
  {
    "rank": 30,
    "title": "Die For You",
    "artist": "The Weeknd",
    "streams": 2.86,
    "genre": "R&B",
    "year": 2016,
    "energy": 0.55,
    "danceability": 0.4,
    "valence": 0.32,
    "bpm": 95.0
  },
  {
    "rank": 31,
    "title": "Lovely",
    "artist": "Billie Eilish & Khalid",
    "streams": 2.84,
    "genre": "Indie Pop",
    "year": 2018,
    "energy": 0.3,
    "danceability": 0.35,
    "valence": 0.08,
    "bpm": 95.0
  },
  {
    "rank": 32,
    "title": "Uptown Funk",
    "artist": "Mark Ronson ft. Bruno Mars",
    "streams": 2.53,
    "genre": "Funk/Pop",
    "year": 2014,
    "energy": 0.96,
    "danceability": 0.9,
    "valence": 0.82,
    "bpm": 115.0
  },
  {
    "rank": 33,
    "title": "Sweater Weather",
    "artist": "The Neighbourhood",
    "streams": 2.47,
    "genre": "Indie Rock",
    "year": 2013,
    "energy": 0.64,
    "danceability": 0.59,
    "valence": 0.5,
    "bpm": 124.0
  },
  {
    "rank": 34,
    "title": "Cruel Summer",
    "artist": "Taylor Swift",
    "streams": 2.72,
    "genre": "Synth-Pop",
    "year": 2019,
    "energy": 0.7,
    "danceability": 0.55,
    "valence": 0.57,
    "bpm": 170.0
  },
  {
    "rank": 35,
    "title": "Despacito",
    "artist": "Luis Fonsi ft. Daddy Yankee",
    "streams": 2.15,
    "genre": "Reggaeton",
    "year": 2017,
    "energy": 0.81,
    "danceability": 0.69,
    "valence": 0.81,
    "bpm": 178.0
  },
  {
    "rank": 36,
    "title": "Havana",
    "artist": "Camila Cabello ft. Young Thug",
    "streams": 2.13,
    "genre": "Latin Pop",
    "year": 2017,
    "energy": 0.58,
    "danceability": 0.76,
    "valence": 0.61,
    "bpm": 105.0
  },
  {
    "rank": 37,
    "title": "Easy On Me",
    "artist": "Adele",
    "streams": 2.02,
    "genre": "Pop/Soul",
    "year": 2021,
    "energy": 0.26,
    "danceability": 0.34,
    "valence": 0.17,
    "bpm": 62.0
  },
  {
    "rank": 38,
    "title": "Lose Yourself",
    "artist": "Eminem",
    "streams": 1.95,
    "genre": "Hip-Hop",
    "year": 2002,
    "energy": 0.62,
    "danceability": 0.66,
    "valence": 0.26,
    "bpm": 171.0
  },
  {
    "rank": 39,
    "title": "Numb",
    "artist": "Linkin Park",
    "streams": 1.82,
    "genre": "Alt Rock",
    "year": 2003,
    "energy": 0.9,
    "danceability": 0.46,
    "valence": 0.15,
    "bpm": 118.0
  },
  {
    "rank": 40,
    "title": "Smells Like Teen Spirit",
    "artist": "Nirvana",
    "streams": 1.8,
    "genre": "Grunge",
    "year": 1991,
    "energy": 0.9,
    "danceability": 0.5,
    "valence": 0.44,
    "bpm": 117.0
  },
  {
    "rank": 41,
    "title": "Espresso",
    "artist": "Sabrina Carpenter",
    "streams": 1.76,
    "genre": "Pop",
    "year": 2024,
    "energy": 0.73,
    "danceability": 0.8,
    "valence": 0.96,
    "bpm": 104.0
  },
  {
    "rank": 42,
    "title": "Radioactive",
    "artist": "Imagine Dragons",
    "streams": 1.74,
    "genre": "Alt Rock",
    "year": 2012,
    "energy": 0.76,
    "danceability": 0.38,
    "valence": 0.23,
    "bpm": 136.0
  },
  {
    "rank": 43,
    "title": "Running Up That Hill",
    "artist": "Kate Bush",
    "streams": 1.52,
    "genre": "Art Pop",
    "year": 1985,
    "energy": 0.68,
    "danceability": 0.41,
    "valence": 0.25,
    "bpm": 112.0
  },
  {
    "rank": 44,
    "title": "Not Like Us",
    "artist": "Kendrick Lamar",
    "streams": 1.5,
    "genre": "Hip-Hop",
    "year": 2024,
    "energy": 0.72,
    "danceability": 0.82,
    "valence": 0.62,
    "bpm": 101.0
  },
  {
    "rank": 45,
    "title": "good 4 u",
    "artist": "Olivia Rodrigo",
    "streams": 1.48,
    "genre": "Pop Punk",
    "year": 2021,
    "energy": 0.9,
    "danceability": 0.56,
    "valence": 0.65,
    "bpm": 166.0
  },
  {
    "rank": 46,
    "title": "All I Want for Christmas Is You",
    "artist": "Mariah Carey",
    "streams": 2.76,
    "genre": "Holiday Pop",
    "year": 1994,
    "energy": 0.66,
    "danceability": 0.42,
    "valence": 0.78,
    "bpm": 150.0
  },
  {
    "rank": 47,
    "title": "Starboy",
    "artist": "The Weeknd ft. Daft Punk",
    "streams": 2.62,
    "genre": "Synth-Pop",
    "year": 2016,
    "energy": 0.79,
    "danceability": 0.68,
    "valence": 0.5,
    "bpm": 186.0
  },
  {
    "rank": 48,
    "title": "goosebumps",
    "artist": "Travis Scott",
    "streams": 2.59,
    "genre": "Hip-Hop",
    "year": 2016,
    "energy": 0.68,
    "danceability": 0.62,
    "valence": 0.39,
    "bpm": 130.0
  },
  {
    "rank": 49,
    "title": "7 rings",
    "artist": "Ariana Grande",
    "streams": 2.56,
    "genre": "Trap Pop",
    "year": 2019,
    "energy": 0.61,
    "danceability": 0.64,
    "valence": 0.49,
    "bpm": 140.0
  },
  {
    "rank": 50,
    "title": "Die With A Smile",
    "artist": "Lady Gaga & Bruno Mars",
    "streams": 1.84,
    "genre": "Pop",
    "year": 2024,
    "energy": 0.68,
    "danceability": 0.72,
    "valence": 0.55,
    "bpm": 120.0
  },
  {
    "rank": 51,
    "title": "Peaches",
    "artist": "Justin Bieber",
    "streams": 1.6,
    "genre": "R&B/Pop",
    "year": 2021,
    "energy": 0.52,
    "danceability": 0.68,
    "valence": 0.69,
    "bpm": 90.0
  },
  {
    "rank": 52,
    "title": "Falling",
    "artist": "Harry Styles",
    "streams": 2.4,
    "genre": "Pop Rock",
    "year": 2019,
    "energy": 0.43,
    "danceability": 0.43,
    "valence": 0.07,
    "bpm": 88.0
  },
  {
    "rank": 53,
    "title": "Thunder",
    "artist": "Imagine Dragons",
    "streams": 3.49,
    "genre": "Alt Rock",
    "year": 2017,
    "energy": 0.52,
    "danceability": 0.6,
    "valence": 0.55,
    "bpm": 168.0
  },
  {
    "rank": 54,
    "title": "Bad Habits",
    "artist": "Ed Sheeran",
    "streams": 1.62,
    "genre": "Synth-Pop",
    "year": 2021,
    "energy": 0.83,
    "danceability": 0.68,
    "valence": 0.72,
    "bpm": 126.0
  },
  {
    "rank": 55,
    "title": "Butter",
    "artist": "BTS",
    "streams": 1.6,
    "genre": "Funk/Pop",
    "year": 2021,
    "energy": 0.73,
    "danceability": 0.79,
    "valence": 0.74,
    "bpm": 110.0
  },
  {
    "rank": 56,
    "title": "Night Changes",
    "artist": "One Direction",
    "streams": 2.34,
    "genre": "Pop",
    "year": 2014,
    "energy": 0.54,
    "danceability": 0.56,
    "valence": 0.72,
    "bpm": 82.0
  },
  {
    "rank": 57,
    "title": "High Hopes",
    "artist": "Panic! At The Disco",
    "streams": 2.32,
    "genre": "Pop Rock",
    "year": 2018,
    "energy": 0.83,
    "danceability": 0.66,
    "valence": 0.84,
    "bpm": 191.0
  },
  {
    "rank": 58,
    "title": "Riptide",
    "artist": "Vance Joy",
    "streams": 2.5,
    "genre": "Indie Folk",
    "year": 2013,
    "energy": 0.55,
    "danceability": 0.66,
    "valence": 0.82,
    "bpm": 131.0
  },
  {
    "rank": 59,
    "title": "Way Down We Go",
    "artist": "KALEO",
    "streams": 2.29,
    "genre": "Blues Rock",
    "year": 2016,
    "energy": 0.48,
    "danceability": 0.46,
    "valence": 0.28,
    "bpm": 78.0
  },
  {
    "rank": 60,
    "title": "Heather",
    "artist": "Conan Gray",
    "streams": 2.26,
    "genre": "Indie Pop",
    "year": 2020,
    "energy": 0.3,
    "danceability": 0.44,
    "valence": 0.3,
    "bpm": 86.0
  },
  {
    "rank": 61,
    "title": "Mood",
    "artist": "24kGoldn ft. iann dior",
    "streams": 2.2,
    "genre": "Pop Punk",
    "year": 2020,
    "energy": 0.75,
    "danceability": 0.7,
    "valence": 0.6,
    "bpm": 150.0
  },
  {
    "rank": 62,
    "title": "Photograph",
    "artist": "Ed Sheeran",
    "streams": 3.45,
    "genre": "Folk Pop",
    "year": 2014,
    "energy": 0.56,
    "danceability": 0.6,
    "valence": 0.52,
    "bpm": 96.0
  },
  {
    "rank": 63,
    "title": "Love Yourself",
    "artist": "Justin Bieber",
    "streams": 2.93,
    "genre": "Acoustic Pop",
    "year": 2015,
    "energy": 0.38,
    "danceability": 0.62,
    "valence": 0.55,
    "bpm": 102.0
  },
  {
    "rank": 64,
    "title": "Without Me",
    "artist": "Halsey",
    "streams": 2.82,
    "genre": "Pop",
    "year": 2018,
    "energy": 0.69,
    "danceability": 0.58,
    "valence": 0.3,
    "bpm": 130.0
  },
  {
    "rank": 65,
    "title": "Something Just Like This",
    "artist": "The Chainsmokers & Coldplay",
    "streams": 2.9,
    "genre": "EDM/Pop",
    "year": 2017,
    "energy": 0.73,
    "danceability": 0.62,
    "valence": 0.53,
    "bpm": 103.0
  },
  {
    "rank": 66,
    "title": "Positions",
    "artist": "Ariana Grande",
    "streams": 2.65,
    "genre": "R&B/Pop",
    "year": 2020,
    "energy": 0.66,
    "danceability": 0.74,
    "valence": 0.69,
    "bpm": 144.0
  },
  {
    "rank": 67,
    "title": "Roses",
    "artist": "SAINt JHN",
    "streams": 3.42,
    "genre": "Hip-Hop",
    "year": 2016,
    "energy": 0.62,
    "danceability": 0.72,
    "valence": 0.44,
    "bpm": 98.0
  },
  {
    "rank": 68,
    "title": "Thinking Out Loud",
    "artist": "Ed Sheeran",
    "streams": 2.1,
    "genre": "Soul/R&B",
    "year": 2014,
    "energy": 0.44,
    "danceability": 0.78,
    "valence": 0.46,
    "bpm": 79.0
  },
  {
    "rank": 69,
    "title": "Wrecking Ball",
    "artist": "Miley Cyrus",
    "streams": 2.08,
    "genre": "Pop Rock",
    "year": 2013,
    "energy": 0.53,
    "danceability": 0.36,
    "valence": 0.24,
    "bpm": 72.0
  },
  {
    "rank": 70,
    "title": "golden hour",
    "artist": "JVKE",
    "streams": 2.68,
    "genre": "Indie Pop",
    "year": 2022,
    "energy": 0.55,
    "danceability": 0.59,
    "valence": 0.86,
    "bpm": 98.0
  },
  {
    "rank": 71,
    "title": "Unstoppable",
    "artist": "Sia",
    "streams": 2.96,
    "genre": "Pop",
    "year": 2016,
    "energy": 0.44,
    "danceability": 0.64,
    "valence": 0.55,
    "bpm": 84.0
  },
  {
    "rank": 72,
    "title": "abcdefu",
    "artist": "GAYLE",
    "streams": 1.99,
    "genre": "Pop Punk",
    "year": 2021,
    "energy": 0.85,
    "danceability": 0.58,
    "valence": 0.68,
    "bpm": 144.0
  },
  {
    "rank": 73,
    "title": "Sunroof",
    "artist": "Nicky Youre & Dazy",
    "streams": 1.64,
    "genre": "Indie Pop",
    "year": 2021,
    "energy": 0.8,
    "danceability": 0.76,
    "valence": 0.96,
    "bpm": 138.0
  },
  {
    "rank": 74,
    "title": "Beautiful Things",
    "artist": "Benson Boone",
    "streams": 1.4,
    "genre": "Pop Rock",
    "year": 2024,
    "energy": 0.68,
    "danceability": 0.46,
    "valence": 0.46,
    "bpm": 97.0
  },
  {
    "rank": 75,
    "title": "middle of the night",
    "artist": "Elley Duh\u00e9",
    "streams": 2.7,
    "genre": "Pop",
    "year": 2022,
    "energy": 0.62,
    "danceability": 0.62,
    "valence": 0.44,
    "bpm": 97.0
  },
  {
    "rank": 76,
    "title": "Savage Love",
    "artist": "Jawsh 685 & Jason Derulo",
    "streams": 1.86,
    "genre": "Pop",
    "year": 2020,
    "energy": 0.69,
    "danceability": 0.76,
    "valence": 0.65,
    "bpm": 107.0
  },
  {
    "rank": 77,
    "title": "APT.",
    "artist": "ROSE & Bruno Mars",
    "streams": 1.66,
    "genre": "K-Pop/Pop",
    "year": 2024,
    "energy": 0.79,
    "danceability": 0.86,
    "valence": 0.88,
    "bpm": 145.0
  },
  {
    "rank": 78,
    "title": "Welcome To The Black Parade",
    "artist": "My Chemical Romance",
    "streams": 1.78,
    "genre": "Alt Rock",
    "year": 2006,
    "energy": 0.85,
    "danceability": 0.31,
    "valence": 0.12,
    "bpm": 64.0
  },
  {
    "rank": 79,
    "title": "Iris",
    "artist": "Goo Goo Dolls",
    "streams": 1.72,
    "genre": "Alt Rock",
    "year": 1998,
    "energy": 0.28,
    "danceability": 0.33,
    "valence": 0.14,
    "bpm": 77.0
  },
  {
    "rank": 80,
    "title": "Astronaut In The Ocean",
    "artist": "Masked Wolf",
    "streams": 1.7,
    "genre": "Hip-Hop",
    "year": 2019,
    "energy": 0.79,
    "danceability": 0.72,
    "valence": 0.38,
    "bpm": 145.0
  },
  {
    "rank": 81,
    "title": "Levii's Jeans",
    "artist": "Beyonc\u00e9 ft. Post Malone",
    "streams": 1.68,
    "genre": "Country/Pop",
    "year": 2024,
    "energy": 0.65,
    "danceability": 0.72,
    "valence": 0.72,
    "bpm": 106.0
  },
  {
    "rank": 82,
    "title": "Lose Control",
    "artist": "Teddy Swims",
    "streams": 1.65,
    "genre": "R&B/Soul",
    "year": 2023,
    "energy": 0.55,
    "danceability": 0.6,
    "valence": 0.64,
    "bpm": 90.0
  },
  {
    "rank": 83,
    "title": "Too Sweet",
    "artist": "Hozier",
    "streams": 1.63,
    "genre": "Indie Folk",
    "year": 2024,
    "energy": 0.48,
    "danceability": 0.62,
    "valence": 0.68,
    "bpm": 86.0
  },
  {
    "rank": 84,
    "title": "Sign of the Times",
    "artist": "Harry Styles",
    "streams": 2.05,
    "genre": "Art Rock",
    "year": 2017,
    "energy": 0.53,
    "danceability": 0.3,
    "valence": 0.1,
    "bpm": 90.0
  },
  {
    "rank": 85,
    "title": "Adore You",
    "artist": "Harry Styles",
    "streams": 1.9,
    "genre": "Indie Pop",
    "year": 2019,
    "energy": 0.76,
    "danceability": 0.56,
    "valence": 0.66,
    "bpm": 108.0
  },
  {
    "rank": 86,
    "title": "Arcade",
    "artist": "Duncan Laurence",
    "streams": 1.88,
    "genre": "Indie Pop",
    "year": 2019,
    "energy": 0.3,
    "danceability": 0.34,
    "valence": 0.1,
    "bpm": 86.0
  },
  {
    "rank": 87,
    "title": "See You Again",
    "artist": "Wiz Khalifa ft. Charlie Puth",
    "streams": 1.42,
    "genre": "Hip-Hop/Pop",
    "year": 2015,
    "energy": 0.37,
    "danceability": 0.53,
    "valence": 0.48,
    "bpm": 80.0
  },
  {
    "rank": 88,
    "title": "Attention",
    "artist": "Charlie Puth",
    "streams": 1.44,
    "genre": "Pop",
    "year": 2017,
    "energy": 0.68,
    "danceability": 0.78,
    "valence": 0.6,
    "bpm": 107.0
  },
  {
    "rank": 89,
    "title": "In The Stars",
    "artist": "Benson Boone",
    "streams": 1.68,
    "genre": "Pop",
    "year": 2023,
    "energy": 0.44,
    "danceability": 0.51,
    "valence": 0.42,
    "bpm": 80.0
  },
  {
    "rank": 90,
    "title": "Kiss Me More",
    "artist": "Doja Cat ft. SZA",
    "streams": 2.23,
    "genre": "Pop/R&B",
    "year": 2021,
    "energy": 0.66,
    "danceability": 0.78,
    "valence": 0.8,
    "bpm": 115.0
  },
  {
    "rank": 91,
    "title": "End Of Beginning",
    "artist": "Djo",
    "streams": 1.6,
    "genre": "Indie Rock",
    "year": 2022,
    "energy": 0.64,
    "danceability": 0.52,
    "valence": 0.44,
    "bpm": 139.0
  },
  {
    "rank": 92,
    "title": "Ribs",
    "artist": "Lorde",
    "streams": 1.54,
    "genre": "Indie Pop",
    "year": 2013,
    "energy": 0.44,
    "danceability": 0.38,
    "valence": 0.22,
    "bpm": 104.0
  },
  {
    "rank": 93,
    "title": "Lemon Tree",
    "artist": "Fools Garden",
    "streams": 1.46,
    "genre": "Pop Rock",
    "year": 1996,
    "energy": 0.76,
    "danceability": 0.74,
    "valence": 0.86,
    "bpm": 139.0
  },
  {
    "rank": 94,
    "title": "Bliss",
    "artist": "Muse",
    "streams": 1.62,
    "genre": "Alt Rock",
    "year": 2001,
    "energy": 0.82,
    "danceability": 0.44,
    "valence": 0.44,
    "bpm": 154.0
  },
  {
    "rank": 95,
    "title": "Stumblin' In",
    "artist": "Cyril & Violet Skies",
    "streams": 1.58,
    "genre": "Pop",
    "year": 2023,
    "energy": 0.54,
    "danceability": 0.66,
    "valence": 0.76,
    "bpm": 90.0
  },
  {
    "rank": 96,
    "title": "Electricity",
    "artist": "Silk City & Dua Lipa",
    "streams": 1.92,
    "genre": "EDM/Pop",
    "year": 2018,
    "energy": 0.88,
    "danceability": 0.76,
    "valence": 0.72,
    "bpm": 143.0
  },
  {
    "rank": 97,
    "title": "Blinding Lights (Remix)",
    "artist": "The Weeknd & Rosal\u00eda",
    "streams": 1.44,
    "genre": "Synth-Pop",
    "year": 2020,
    "energy": 0.8,
    "danceability": 0.54,
    "valence": 0.36,
    "bpm": 171.0
  },
  {
    "rank": 98,
    "title": "Falling For You",
    "artist": "Peachy feat. mxmtoon",
    "streams": 1.56,
    "genre": "Indie Pop",
    "year": 2018,
    "energy": 0.42,
    "danceability": 0.64,
    "valence": 0.72,
    "bpm": 150.0
  },
  {
    "rank": 99,
    "title": "Laugh Now Cry Later",
    "artist": "Drake ft. Lil Durk",
    "streams": 3.05,
    "genre": "Hip-Hop",
    "year": 2020,
    "energy": 0.62,
    "danceability": 0.82,
    "valence": 0.55,
    "bpm": 142.0
  },
  {
    "rank": 100,
    "title": "Shake It Off",
    "artist": "Taylor Swift",
    "streams": 1.6,
    "genre": "Pop",
    "year": 2014,
    "energy": 0.8,
    "danceability": 0.65,
    "valence": 0.94,
    "bpm": 160.0
  }
];